// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkaM1CfNMbyv8tGZyWMYBIku3EGpPw6YY',
    appId: '1:686636921631:web:d8d0e3b6df426adb1f362a',
    messagingSenderId: '686636921631',
    projectId: 'financy-app-dmais',
    authDomain: 'financy-app-dmais.firebaseapp.com',
    storageBucket: 'financy-app-dmais.appspot.com',
    measurementId: 'G-V8WK4Q2BM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsZB_al8bzv_rZhcVy-eDOPNun3jwzyqM',
    appId: '1:686636921631:android:c54cbe6548f71e481f362a',
    messagingSenderId: '686636921631',
    projectId: 'financy-app-dmais',
    storageBucket: 'financy-app-dmais.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvimLtP_jyHl4bX_vf12X2WhpvSRkoj8',
    appId: '1:686636921631:ios:f4c216cb518647531f362a',
    messagingSenderId: '686636921631',
    projectId: 'financy-app-dmais',
    storageBucket: 'financy-app-dmais.appspot.com',
    iosClientId: '686636921631-qovt611vdbg3muc1f4hcpbj6bv9virki.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinancy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvimLtP_jyHl4bX_vf12X2WhpvSRkoj8',
    appId: '1:686636921631:ios:f4c216cb518647531f362a',
    messagingSenderId: '686636921631',
    projectId: 'financy-app-dmais',
    storageBucket: 'financy-app-dmais.appspot.com',
    iosClientId: '686636921631-qovt611vdbg3muc1f4hcpbj6bv9virki.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinancy',
  );
}
